server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:logback-dev.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.143.175:3306/financial
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari.minimum-idle: 5
    hikari.maximum-pool-size: 15
    hikari.auto-commit: true
    hikari.idle-timeout: 30000
    hikari.pool-name: DatebookHikariCP
    hikari.max-lifetime: 1800000
    hikari.connection-timeout: 30000
    hikari.connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true


########## custom configuration ##########
test:
  test: test
