server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:logback-prod.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/canal_tsdb
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari.minimum-idle: 5
    hikari.maximum-pool-size: 15
    hikari.auto-commit: true
    hikari.idle-timeout: 30000
    hikari.pool-name: DatebookHikariCP
    hikari.max-lifetime: 1800000
    hikari.connection-timeout: 30000
    hikari.connection-test-query: SELECT 1

