server:
  port: 8001

mybatis:
  type-aliases-package: org.inh3rit.financial.model
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    default-statement-timeout: 80
    lazy-loading-enabled: true

logging:
  config: classpath:logback-dev.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.143.175:3306/financial
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari.minimum-idle: 5
    hikari.maximum-pool-size: 15
    hikari.auto-commit: true
    hikari.idle-timeout: 30000
    hikari.pool-name: DatebookHikariCP
    hikari.max-lifetime: 1800000
    hikari.connection-timeout: 30000
    hikari.connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true


########## custom configuration ##########
test:
  test: test
